"""initial migration

Revision ID: 664d83e3c740
Revises: None
Create Date: 2016-04-14 21:33:15.563000

"""

# revision identifiers, used by Alembic.
revision = '664d83e3c740'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
