"""initial migration

Revision ID: aee21c4cb36b
Revises: e9a19129bc35
Create Date: 2016-04-15 22:28:54.026000

"""

# revision identifiers, used by Alembic.
revision = 'aee21c4cb36b'
down_revision = 'e9a19129bc35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
